version: 2  # use CircleCI 2.0
jobs: # basic units of work in a run
  build:
    docker:
      - image: alpine:latest
        environment:
          TST_VAR: "container"
          OTHER_VAR: "$TACO_FLAVOUR"
    environment:
      - TST_VAR: "job"
    steps:
      - checkout
      - run:
          name: "custom vairables"
          environment:
            TST_VAR: "step"
          command: |
            echo 'export TST_VAR="shell"' >> $BASH_ENV
            source $BASH_ENV
            echo $TST_VAR
            echo $OTHER_VAR


