version: 2  # use CircleCI 2.0
jobs: # basic units of work in a run
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "custom vairables"
          command: |
            echo 'export TST_VAR="shell"' >> $BASH_ENV
            echo $BASH_ENV
            echo $TST_VAR


